/*
 * Robot Wars API
 * Eine Api für das Spiel Robot Wars
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * N,S,E,W,NW,NE,SW,SE,
 */
@JsonAdapter(Align.Adapter.class)
public enum Align {
  @SerializedName("N")
  N("N"),
  @SerializedName("S")
  S("S"),
  @SerializedName("E")
  E("E"),
  @SerializedName("W")
  W("W"),
  @SerializedName("NW")
  NW("NW"),
  @SerializedName("NE")
  NE("NE"),
  @SerializedName("SW")
  SW("SW"),
  @SerializedName("SE")
  SE("SE");

  private String value;

  Align(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Align fromValue(String input) {
    for (Align b : Align.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Align> {
    @Override
    public void write(final JsonWriter jsonWriter, final Align enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public Align read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return Align.fromValue((String)(value));
    }
  }
}
