/*
 * Robot Wars API
 * Eine Api für das Spiel Robot Wars
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Move;
import io.swagger.client.model.PlayerRobot;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Game
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-17T06:35:04.896175349Z[GMT]")

public class Game {
  @SerializedName("id")
  private String id = null;

  @SerializedName("map")
  private String map = null;

  @SerializedName("player")
  private List<PlayerRobot> player = null;

  @SerializedName("moves")
  private List<Move> moves = new ArrayList<Move>();

  /**
   * STARTED, INITIAL, END
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    @SerializedName("STARTED")
    STARTED("STARTED"),
    @SerializedName("INITIAL")
    INITIAL("INITIAL"),
    @SerializedName("END")
    END("END");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  public Game id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Einzigartige Id des Spiels
   * @return id
  **/
  @Schema(example = "1234", required = true, description = "Einzigartige Id des Spiels")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Game map(String map) {
    this.map = map;
    return this;
  }

   /**
   * Map Id
   * @return map
  **/
  @Schema(example = "1234", required = true, description = "Map Id")
  public String getMap() {
    return map;
  }

  public void setMap(String map) {
    this.map = map;
  }

  public Game player(List<PlayerRobot> player) {
    this.player = player;
    return this;
  }

  public Game addPlayerItem(PlayerRobot playerItem) {
    if (this.player == null) {
      this.player = new ArrayList<PlayerRobot>();
    }
    this.player.add(playerItem);
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @Schema(description = "")
  public List<PlayerRobot> getPlayer() {
    return player;
  }

  public void setPlayer(List<PlayerRobot> player) {
    this.player = player;
  }

  public Game moves(List<Move> moves) {
    this.moves = moves;
    return this;
  }

  public Game addMovesItem(Move movesItem) {
    this.moves.add(movesItem);
    return this;
  }

   /**
   * Get moves
   * @return moves
  **/
  @Schema(required = true, description = "")
  public List<Move> getMoves() {
    return moves;
  }

  public void setMoves(List<Move> moves) {
    this.moves = moves;
  }

  public Game status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * STARTED, INITIAL, END
   * @return status
  **/
  @Schema(example = "STARTED", description = "STARTED, INITIAL, END")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Game game = (Game) o;
    return Objects.equals(this.id, game.id) &&
        Objects.equals(this.map, game.map) &&
        Objects.equals(this.player, game.player) &&
        Objects.equals(this.moves, game.moves) &&
        Objects.equals(this.status, game.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, map, player, moves, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Game {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    map: ").append(toIndentedString(map)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    moves: ").append(toIndentedString(moves)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
