/*
 * Robot Wars API
 * Eine Api für das Spiel Robot Wars
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PlayerRobot
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-28T13:24:19.900928858Z[GMT]")

public class PlayerRobot {
  @SerializedName("playerId")
  private String playerId = null;

  @SerializedName("robotId")
  private String robotId = null;

  public PlayerRobot playerId(String playerId) {
    this.playerId = playerId;
    return this;
  }

   /**
   * Einzigartige Id des Spielers
   * @return playerId
  **/
  @Schema(example = "1234", description = "Einzigartige Id des Spielers")
  public String getPlayerId() {
    return playerId;
  }

  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }

  public PlayerRobot robotId(String robotId) {
    this.robotId = robotId;
    return this;
  }

   /**
   * Einzigartige Id des genutzten Roboters
   * @return robotId
  **/
  @Schema(example = "1234", description = "Einzigartige Id des genutzten Roboters")
  public String getRobotId() {
    return robotId;
  }

  public void setRobotId(String robotId) {
    this.robotId = robotId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerRobot playerRobot = (PlayerRobot) o;
    return Objects.equals(this.playerId, playerRobot.playerId) &&
        Objects.equals(this.robotId, playerRobot.robotId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, robotId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerRobot {\n");
    
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    robotId: ").append(toIndentedString(robotId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
